### ISSUE TITLE
Octoprint user can't access /dev/video*, needs to be added to the video group

### ISSUE THREAD

**Issue by rozinky** [tquiggle/OctoBox#5]
Thanks for making this thing, it's made setting up octoprint a lot easier.

Issue: Octoprint user can't access /dev/video*, specifically this causes an issue with the Camera Settings plugin because it directly accesses the webcam.

After I added it to the video group it worked fine, but you might update your install/scripts to do this for future boxes.

**Comment by tquiggle** [comment]
Thanks Jason.  I don't personally use a camera and have never messed with the Camera Settings plugin.  I'll add the 'octoprint' user to the group 'video' for the base image installed on all future OctoBoxes.

**Comment by tquiggle** [comment]
Fixed in all recent OctoBox images (and has been for quite some time).  Thanks rozinky for bringing this to my attention.
